version: "3.9"
services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - "~/Data/survey-backend/postgres:/var/lib/postgresql/data"
    env_file:
      - .env
  
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/survey-backend"
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

